### ISSUE TITLE
Can you tell me what hardware connected to the pc 

### ISSUE THREAD

**Issue by didjado** [IRNAS/nrf52-zephyr-mcuboot-ble-dfu-python#1]
Hi 

i have been looking for a way of doing the dfu to zephyr in the nrf collection of products

what i cannot figure out is what hardware you have connected this script to... was it a dev kit or was it native bluetooth in the PC

and if it is a nrf dev kit what was the firmware loaded on the device

**Comment by SloMusti** [comment]
@didjado this works with the PC BLE adapter, no nrf dev kit required. RUns on Raspberry PI as well.
